---
## perform stop service for alertmanager

- name: Stop service alertmanager if started
  become: yes
  service:
    name: alertmanager
    state: stopped

## SVN export local copy of prometheus values file

- name: local SVN command to checkout export file locally on devops box
  delegate_to: 127.0.0.1
  shell: svn export https://PATH TO REPO
  register: result_svn
- debug: var=result_svn.stdout

## ansible copy checked out file to remote host
## register the variable and display the backup_file file name in output

- name: Copy new alertmanager config file and backup existing file
  become: yes
  copy:
    src: /workspace/checkout/alertmanager.yml
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: wheel
    mode: u+rw,g+r,o+r
    backup: yes
  register: result_backup_path
- debug: var=result_backup_path.backup_file

## use newly registered backup file name variable to move backup file
## backup files should not be stored in the helm charts folder, there is a file size limit

- name: Move ansible created backup file to ansible_config_backups
  become: yes
  shell: mv {{ result_backup_path.backup_file }} /etc/alertmanager/BACKUP DIR NAME/
  args:
    chdir: /etc/alertmanager/
  register: result_shell_move
- debug: var=result_shell_move.stdout_lines

## perform start service for alertmanager

- name: Start service alertmanager if not started
  become: yes
  service:
    name: alertmanager
    state: started
